// Build-time defaults, used by `ng serve` and as a fallback when no
// runtime config (src/assets/env.js, generated by the Docker entrypoint
// from the API_URL env var) is present. See RuntimeConfigService.
export const environment = {
  production: false,
  apiUrl: 'http://localhost:8080/api',
};
